pipeline {
    agent any

    stages {
        stage('Stage 1') {
            steps {

                echo "This is my first jenkins pipeline"
                
                
            }
        }
    }
}
