pipeline {
    agent any

    environment {
        DEMO = '1.0'
    }

    stages {
        stage('Stage 1') {
            steps {

                echo "This is my first jenkins pipeline with $DEMO and ${env.BUILD_ID} and $BUILD_ID"

                sh "echo 'This is my first jenkins pipeline with $DEMO and $BUILD_ID'"

                sh "docker --version"
                
                
            }
        }
    }
}
