node {
    // Define the environment variable

    env.DEMO = "1.1"

    stage("Stage 1") {
         echo "This is my first jenkins pipeline with $DEMO and ${env.BUILD_ID} and $BUILD_ID"

                sh "echo 'This is my first jenkins pipeline with $DEMO and $BUILD_ID'"

                sh "docker --version"
    }
}